### ISSUE TITLE
dns异常

### ISSUE THREAD

**Issue by 805528119** [SunBK201/UA3F#10]
使用国内版clash参考配置后，访问部分网站包括检测ua网站会出现dns错误，改hosts后能正常访问。后来发现只有停用openclash中的dns本地劫持才能正常访问

**Comment by SunBK201** [comment]
本地 DNS 劫持选择使用 Dnsmasq 转发，不要使用防火墙转发

**Comment by 805528119** [comment]
已解决，通过修改
