### ISSUE TITLE
ua3f启动不了

### ISSUE THREAD

**Issue by Wenmenghan** [SunBK201/UA3F#12]
![屏幕截图 2024-05-08 015334](https://github.com/SunBK201/UA3F/assets/84793941/f439bbba-221a-4bc4-915b-df0251f20735)
启动不了，日志没有任何记录

**Comment by Wenmenghan** [comment]
---- 回复的原邮件 ----
***@***.***>发送日期2024年5月8日 ***@***.***>***@***.***>,
***@***.***>主题Re: [SunBK201/UA3F] ua3f启动不了 (Issue #12)
请先确保你的 openwrt 版本是主流发型版

**Comment by SunBK201** [comment]
呃.. 你的回复似乎有问题？
