### ISSUE TITLE
对于部分域名，建立新连接速度极慢

### ISSUE THREAD

**Issue by Starseeker-H** [SunBK201/UA3F#15]
典型如明日方舟，登录时需要花费极长的时间才能登录，经clash面板发现在尝试登录时，每次都要停顿半分钟才会建立一个新连接，然后开始等下一个连接，整个登录流程中需要建立至少七个不同域名的连接，结果是最后一步时最开始的连接已经被clash自己掐掉了（过三分钟了），登录失败。

类似的有bing，经常要花非常长时间才能打开，反例就是b站，随便开（

之后尝试给CN组不走ua3f的代理走机场，立马就正常了，所以确认应该是ua3f的问题

这是可能相关的日志
[test.txt](https://github.com/user-attachments/files/16997565/test.txt)

**Comment by SunBK201** [comment]
你的OpenWrt版本是什么？

**Comment by Starseeker-H** [comment]
> 你的OpenWrt版本是什么？

[Powered by ImmortalWrt (23.05)](https://github.com/openwrt/luci) / [ArgonTheme v2.3.1](https://github.com/jerrykuku/luci-theme-argon) / Build by innmonkey v2024.09

恩山下的 ImmortalWrt 固件，源链接 https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8364734&highlight=openwrt%2B%E5%9B%BA%E4%BB%B6

>  4.本固件主要包含以下插件：docker、mosdns、pushbot、Jellyfin、filebrowser、ope***h、qbittorrent、transmission、阿里DDNS、易有云。

还不会自己编译固件改硬盘大小，所以只能找尽可能简洁的了

**Comment by SunBK201** [comment]
有没有尝试过使用 ShellClash 和 官方 OpenWrt ？

**Comment by NuoFang6** [comment]
通常不会出现这种情况，我注意到你的日志中出现了 1.1.1.1 这个不应直连的 dns 使用80端口通过了 ua3f 直连，可能是 clash 的 DNS 配置 或者分流规则错误导致的

![image](https://github.com/user-attachments/assets/00da1b37-3fc2-40c5-973e-545fde323ee5)

**Comment by Starseeker-H** [comment]
> 有没有尝试过使用 ShellClash 和 官方 OpenWrt ？

刚刚尝试了使用官方 ImmortalWrt ，仅安装 openclash 与 ua3f ，表现正常，应该是原固件不知道动了什么设置导致的……
