### ISSUE TITLE
出现 panic 报错

### ISSUE THREAD

**Issue by NuoFang6** [SunBK201/UA3F#16]
日志如下，似乎没有造成断网

Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]: panic: runtime error: index out of range [-1]
Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]:
Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]: goroutine 843830 [running]:
Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]: ua3f/http.(*HTTPParser).Parse(0x400044de50, {0x400058a000, 0x10b, 0x2000})
Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]: 	ua3f/http/http.go:227 +0x84c
Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]: main.CopyPileline({0x164808, 0x40001043c0}, {0x164528, 0x400006e3e0}, {0x4000064bd0, 0x13})
Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]: 	./ua3f.go:416 +0x7c0
Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]: main.Socks5Forward.func2({0x165850?, 0x40001043c0}, {0x165850?, 0x400006e3e0})
Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]: 	./ua3f.go:370 +0xf0
Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]: created by main.Socks5Forward in goroutine 843711
Sat Sep 14 19:44:47 2024 daemon.err ua3f[18867]: 	./ua3f.go:378 +0x2ac

配置：
![image](https://github.com/user-attachments/assets/915f2993-8a4d-49aa-816d-7b95bd210e0b)

**Comment by SunBK201** [comment]
这个问题能够稳定复现吗？

**Comment by NuoFang6** [comment]
> 这个问题能够稳定复现吗？

不能，目前仅出现过一次

**Comment by SunBK201** [comment]
应该是某处越界访问了，近期会进行版本更新，优化日志输出方便确认问题。
