### ISSUE TITLE
能否添加自定义UA规则匹配

### ISSUE THREAD

**Issue by alphime** [SunBK201/UA3F#17]
比如用正则表达式
或者比如可以按照括号外判断空格有几个，一旦检测到三个点...就补上原始UA空格后面的内容

**Comment by SunBK201** [comment]
能进一步描述「自定义 UA 规则匹配」的功能和需求吗？为什么需要这个功能？

**Comment by SunBK201** [comment]
UA3F v0.5.0 发布，支持自定义 UA 规则匹配：User-Agent Regex Pattern 为 User-Agent 正则表达式规则。如果流量中的 User-Agent 匹配该正则表达式，则会被修改为 User-Agent 字段的内容，否则不会被修改；如果该字段为空，则所有流量 User-Agent 都会被修改。默认 (iPhone|iPad|Android|Macintosh|Windows|Linux)，即只修改携带设备与系统信息的 User-Agent。

**Comment by alphime** [comment]
有没有示例操作
> UA3F v0.5.0 发布，支持自定义 UA 规则匹配：User-Agent Regex Pattern 为 User-Agent 正则表达式规则。如果流量中的 User-Agent 匹配该正则表达式，则会被修改为 User-Agent 字段的内容，否则不会被修改；如果该字段为空，则所有流量 User-Agent 都会被修改。默认 (iPhone|iPad|Android|Macintosh|Windows|Linux)，即只修改携带设备与系统信息的 User-Agent。

**Comment by alphime** [comment]
这个能支持替换ua的指定内容吗，比如将ua的android替换成windows，其它内容不变保留
> UA3F v0.5.0 发布，支持自定义 UA 规则匹配：User-Agent Regex Pattern 为 User-Agent 正则表达式规则。如果流量中的 User-Agent 匹配该正则表达式，则会被修改为 User-Agent 字段的内容，否则不会被修改；如果该字段为空，则所有流量 User-Agent 都会被修改。默认 (iPhone|iPad|Android|Macintosh|Windows|Linux)，即只修改携带设备与系统信息的 User-Agent。

**Comment by SunBK201** [comment]
暂时不支持

**Comment by SunBK201** [comment]
UA3F v0.6.0 发布,支持正则表达式匹配部分替换 Partial Replace: 开启后只替换 User-Agent Regex Pattern 中匹配到的部分。该选项仅在 User-Agent Regex Pattern 不为空时生效。
