### ISSUE TITLE
大佬，ShellClash报warming，ua3f不生效

### ISSUE THREAD

**Issue by langzhu3238** [SunBK201/UA3F#20]
clash正常设置，然后报warming
![image](https://github.com/user-attachments/assets/b55695ff-c747-42c2-b90d-92d6daa8306f)
然后ua3f无法正常启动
![image](https://github.com/user-attachments/assets/27cee4de-4dfc-462c-9571-bea4ed27e3db)
UA无法代理
![image](https://github.com/user-attachments/assets/98c7620c-1920-4553-8be2-bff98d4a9c12)
![image](https://github.com/user-attachments/assets/9239b705-bf35-4d45-ba6d-d043a2b21bc8)
求帮助

**Comment by SunBK201** [comment]
似乎你的clash没有正常运行

**Comment by langzhu3238** [comment]
请问是我的clash安卓错误吗
我用的是export url='https://fastly.jsdelivr.net/gh/juewuy/ShellCrash@master' && sh -c "$(curl -kfsSl $url/install.sh)" && source /etc/profile &> /dev/null这个源进行下载，安装了稳定版。
还是说是其他错误引起的
我用的是redmi ac2100

**Comment by langzhu3238** [comment]
我更新了配置文件依然报warming，crash没有正常启动
![image](https://github.com/user-attachments/assets/06a5b661-96d5-4493-aba9-ffd380b11d00)

**Comment by SunBK201** [comment]
根据你的 log，似乎你的 OpenWrt 内核缺失 nftables 相关模块？

**Comment by 1257278699** [comment]
该怎么办大佬

**Comment by langzhu3238** [comment]
> OpenWrt 内核缺失 nftables 相关模块
请问现在要怎么添加呢？
还是要重新打包固件，重新打包的话要加上哪些模块呢？

**Comment by langzhu3238** [comment]
@SunBK201 

> > OpenWrt 内核缺失 nftables 相关模块
> > 请问现在要怎么添加呢？
> > 还是要重新打包固件，重新打包的话要加上哪些模块呢？

**Comment by 1257278699** [comment]
![IMG_20240922_003620.jpg](https://github.com/user-attachments/assets/f5b903cc-29f9-4939-b2f3-92125232369b)

我也安装失败了

**Comment by SunBK201** [comment]
> > OpenWrt 内核缺失 nftables 相关模块
> > 请问现在要怎么添加呢？
> > 还是要重新打包固件，重新打包的话要加上哪些模块呢？

可以尝试使用官方固件

**Comment by SunBK201** [comment]
> ![IMG_20240922_003620.jpg](https://private-user-images.githubusercontent.com/172070025/369635208-f5b903cc-29f9-4939-b2f3-92125232369b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzY5NjcsIm5iZiI6MTcyNjkzNjY2NywicGF0aCI6Ii8xNzIwNzAwMjUvMzY5NjM1MjA4LWY1YjkwM2NjLTI5ZjktNDkzOS1iMmYzLTkyMTI1MjMyMzY5Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxNjM3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTFmYWEyZDE0Njk3ZTI0OWUzYzJhYWM5MzI4NWMxYmIxMmFkMmZhMjBhODRjMzhiZGJiZmRiMWUwZmNlNDM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j1xa5aqS4GCdhd7z3a5QowV5VTaN_byUqV18tVbHT8A)
> 
> 我也安装失败了

这是网络问题，可以尝试重复执行安装脚本几次

**Comment by langzhu3238** [comment]
> > > OpenWrt 内核缺失 nftables 相关模块
> > > 请问现在要怎么添加呢？
> > > 还是要重新打包固件，重新打包的话要加上哪些模块呢？
> 
> 可以尝试使用官方固件

刷入官方固件后
![image](https://github.com/user-attachments/assets/7e703d77-5509-4d13-ac83-0ec30c2d8dde)
就变成了这样，而且无网络连接，且问题没有解决，依然报warming
![image](https://github.com/user-attachments/assets/0890f3d4-4720-4221-8b36-f75fa7f82cc8)

**Comment by 1257278699** [comment]
这个又是因为什么原因呢大佬![IMG_20240922_092146.jpg](https://github.com/user-attachments/assets/31cf6c6f-d175-40d9-9dbc-5b7151c486b1)

**Comment by 1257278699** [comment]
还是一样![IMG_20240922_112013.jpg](https://github.com/user-attachments/assets/cef29812-9b2e-48d3-ab3a-f0caf65375f7)

**Comment by langzhu3238** [comment]
@SunBK201 
![PixPin_2024-09-22_13-14-42](https://github.com/user-attachments/assets/a9d3436d-4d34-44d7-8b6a-bcc4763ffb7a)
在运行ua3f时还有这个提示

**Comment by langzhu3238** [comment]
@SunBK201 我重置了路由，重新刷入官方固件后依然报warming

**Comment by SunBK201** [comment]
> warming

warming 不是错误，很多情况下是正常的

**Comment by langzhu3238** [comment]
> > warming
> 
> warming 不是错误，很多情况下是正常的

晕，那ua3f不生效的原因找不到了，求解

**Comment by WWWyeye** [comment]
解决了吗哥，我也是这种问题

**Comment by langzhu3238** [comment]
> 解决了吗哥，我也是这种问题

没有，还是无法生效，我按readme上的每一步都重做了

**Comment by WWWyeye** [comment]
> > 解决了吗哥，我也是这个问题
> 
> 没有，还是无法生效，我按readme上的每一步都重做了

我用ua2f，还是一样会被校园网电信宽带断网5分钟，你实现防代理检测了吗？

**Comment by langzhu3238** [comment]
> > > 解决了吗哥，我也是这个问题
> > 
> > 
> > 没有，还是无法生效，我按readme上的每一步都重做了
> 
> 我用ua2f，还是一样会被校园网电信宽带断网5分钟，你实现防代理检测了吗？

没有，多用户一样会被检测断网，但代理vpn没有检测🧐

**Comment by WWWyeye** [comment]
> > > > 解决了吗哥，我也是这个问题
> > > 
> > > 
> > > 没有，还是无法生效，我按readme上的每一步都重做了
> > 
> > 
> > 我用ua2f，还是一样会被接入电信电信宽带断网5分钟，你实现防代理检测了吗？
> 
> 没有，多用户一样会被检测断网，但代理vpn没有检测🧐

啥意思，是使用代理vpn后路由器开wifi后多用户连接没有被检测还是
              只会检测多用户断网，不会因为你代理vpn而断网？

**Comment by langzhu3238** [comment]
> > > > > 解决了吗哥，我也是这个问题
> > > > 
> > > > 
> > > > 没有，还是无法生效，我按readme上的每一步都重做了
> > > 
> > > 
> > > 我用ua2f，还是一样会被接入电信电信宽带断网5分钟，你实现防代理检测了吗？
> > 
> > 
> > 没有，多用户一样会被检测断网，但代理vpn没有检测🧐
> 
> 啥意思，是使用代理vpn后路由器开wifi后多用户连接没有被检测还是 只会检测多用户断网，不会因为你代理vpn而断网？

只会多用户断网

**Comment by WWWyeye** [comment]
哦哦好滴

**Comment by SunBK201** [comment]
可以试试 v0.6.0 该问题是否还存在？

**Comment by langzhu3238** [comment]
![image](https://github.com/user-attachments/assets/cd7d8a2d-b9e7-4f88-8803-260b560f8fc5)
![image](https://github.com/user-attachments/assets/a6b7b3a6-aba7-4473-b905-1570eabf1da5)
更新时有两个报错且问题依旧存在

**Comment by langzhu3238** [comment]
![image](https://github.com/user-attachments/assets/6be1f2c9-797b-4dfb-b9eb-5289cbb08526)

**Comment by SunBK201** [comment]
> ![image](https://private-user-images.githubusercontent.com/174467606/384689642-cd7d8a2d-b9e7-4f88-8803-260b560f8fc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTI1NDEsIm5iZiI6MTczMTI1MjI0MSwicGF0aCI6Ii8xNzQ0Njc2MDYvMzg0Njg5NjQyLWNkN2Q4YTJkLWI5ZTctNGY4OC04ODAzLTI2MGI1NjBmOGZjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNTI0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjljYjdmYWM3MDJlOTg2YzkyMDFkYjU2MTA0YzBlMGJhNTQwZmVmM2ExMzhjYTliYWUzNDdlMmY3M2U2MmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._HYOXVzBeDmSg_fFuO7LJxwtJSfpXgu4ItMRvcpYwlM) ![image](https://private-user-images.githubusercontent.com/174467606/384689651-a6b7b3a6-aba7-4473-b905-1570eabf1da5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTI1NDEsIm5iZiI6MTczMTI1MjI0MSwicGF0aCI6Ii8xNzQ0Njc2MDYvMzg0Njg5NjUxLWE2YjdiM2E2LWFiYTctNDQ3My1iOTA1LTE1NzBlYWJmMWRhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNTI0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmFiNWQ5OThhMjhhYjBiNDAxNjMyMWJkYzY3YTVmNDE0N2QxOWE2ODVhMWI3ZTA3MzlhYWIzNTA2MDgwOGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Um9AsLJA3xavAcXM6OHiQDLyk16_Tn6IkGDp1jbjPQk) 更新时有两个报错且问题依旧存在

这不是 UA3F 的错误，跟 UA3F 无关
