### ISSUE TITLE
从b站视频来的, 有一个问题想请教, 为什么要自己写解析http函数

### ISSUE THREAD

**Issue by huhu415** [SunBK201/UA3F#21]
就是这[一行](https://github.com/SunBK201/UA3F/blob/6bc8f0a87c1dac5e7cc293469683b7a6d1565167/cmd/ua3f.go#L416)为什么没有用包自带的, 就比如这样
```go
		reader := bufio.NewReader(bytes.NewReader(buf[0:nr]))
		http.ReadRequest(reader)
```
这里面是有什么坑么, 如果没有坑的话, 我感觉我可以改一下, 然后交一版pr看看

**Comment by SunBK201** [comment]
Go 的 `http.ReadRequest` 似乎太 high level, 如果只是获取 http 的 header 当然方便，但我们需要做的是在 byte level 拿到 user-agent 的 offset，同时根据 offset 在读取的 buffer 中原地修改。
