### ISSUE TITLE
ua3f装了后显示name ua3f not found

### ISSUE THREAD

**Issue by 1257278699** [SunBK201/UA3F#23]
![IMG_20240922_164344.jpg](https://github.com/user-attachments/assets/787f3f15-c384-4870-b82f-4a75fa38dcf2)

**Comment by 1257278699** [comment]
![IMG_20240922_164344.jpg](https://github.com/user-attachments/assets/a07a2b0a-4916-4879-b909-98131d2d9511)

**Comment by SunBK201** [comment]
可以尝试手动执行命令 `touch /var/log/ua3f.log`

**Comment by 1257278699** [comment]
不行啊，大佬，还是我哪里弄错了![IMG_20240922_181238.jpg](https://github.com/user-attachments/assets/5f0fd26d-c6d9-46c8-b7a9-3a99c8f029be)

**Comment by SunBK201** [comment]
`touch /var/log/ua3f.log` 注意空格

**Comment by 1257278699** [comment]
没发生啥，这样是表示可以了吗![IMG_20240922_181858.jpg](https://github.com/user-attachments/assets/c74c6dfd-2a1d-46f8-b3be-1c4dc3f8a5b6)

**Comment by SunBK201** [comment]
重启 ua3f
