### ISSUE TITLE
打开ua3f 酷安app加载不出来图片

### ISSUE THREAD

**Issue by SkyDreamW** [SunBK201/UA3F#24]
打开ua3f酷安app里面的图片就加载不出来，dns应该是没问题的，因为各种网站也都能打开，关闭ua3f就正常了，我去试了试ua2f也是一样，不知道是什么问题

**Comment by SunBK201** [comment]
部分 app 可能会对 ua 进行校验，可以配置 clash 配置加入指定域名走 DIRECT 规则。

#25

**Comment by 1257278699** [comment]
不知道怎么弄，大佬

**Comment by SunBK201** [comment]
修改 Clash 配置：
```yaml
rules:
  - PROCESS-NAME,ua3f,DIRECT
  - NETWORK,udp,DIRECT
  - <在此处加入你的的规则>,DIRECT
  - MATCH,ua3f
```

**Comment by 1257278699** [comment]
> 修改 Clash 配置：
> ```yaml
> rules:
>   - PROCESS-NAME,ua3f,DIRECT
>   - NETWORK,udp,DIRECT
>   - <在此处加入你的的规则>,DIRECT
>   - MATCH,ua3f
> ```

![IMG_20240923_195935.jpg](https://github.com/user-attachments/assets/fa170937-683a-417d-ba20-2ff225c1abc7)

是在这里修改吗？还是怎么弄，还有在那里加入我的规则，我不会怎么弄什么规则啊？你有教程或者文档什么的吗？我是小白可以看看，就不太会麻烦你了

**Comment by SunBK201** [comment]
clash 规则文档可参考: https://wiki.metacubex.one/config/rules

**Comment by nanfengzhiwoy** [comment]
请问这个怎么找到酷安加载图片的域名
