### ISSUE TITLE
两种端口测试的UA不同

### ISSUE THREAD

**Issue by 1394172394** [SunBK201/UA3F#28]
UA检测时在标准端口测试为FFF，但是非标准端口测试（1234）UA不变。大佬求解答。
额外信息：命令service ua3f.service service时返回not found“ua3f.service”

**Comment by SunBK201** [comment]
检查下clash是否代理了非标准端口

**Comment by 1394172394** [comment]
> 检查下clash是否代理了非标准端口

请问怎么在shellclash中查看代理的端口呢

**Comment by 1394172394** [comment]
> 检查下clash是否代理了非标准端口

已解决，确实是shellcrash没配置好。感谢大佬
