### ISSUE TITLE
shallclash 和ua3f 运行正常 但不工作

### ISSUE THREAD

**Issue by gushi233** [SunBK201/UA3F#29]
使用 cn的 ymal  访问ua检测网站提示就是原ua 不知道问题出在哪里
![QQ图片20241008180011](https://github.com/user-attachments/assets/b0111a25-66c6-4a7a-abca-308f90eef2ce)
![QQ图片20241008175958](https://github.com/user-attachments/assets/948a5d3e-954b-4c8e-a2a9-678418b67990)
目录下无shallclash用户

**Comment by SunBK201** [comment]
根据你提供的日志，UA3F 没有启动，因为 1080 端口被占用了

**Comment by gushi233** [comment]
我除了[shallclash 和ua3f]没有运行任何其他的东西 系统也是我刚刷上的

**Comment by SunBK201** [comment]
你的新刷的系统可能存在其他占用 1080 端口的服务，可以使用 `netstat -antp` 进行排查。

**Comment by gushi233** [comment]
谢谢大佬解答，我看不懂输出结果 可以试着更换其它端口 来实现UA3F么 或者说大佬需要看输出结果么

**Comment by SunBK201** [comment]
可以切换端口，但是 clash 中的 port 配置也要对应修改

**Comment by gushi233** [comment]
找到了占用端口的进程后该怎么办呢 我不太明白  不知道那个进程怎么来的也不知道 该怎么关

**Comment by SunBK201** [comment]
可以使用 `kill` 命令杀掉进程

**Comment by gushi233** [comment]
![QQ图片20241011183603](https://github.com/user-attachments/assets/88485604-f359-4d54-9077-28a5204d380f)
是不是修改yxml这里的port就行了 修改了会有什么弊端么
直接kill掉进程 会出什么别的事么 我看关掉之后断网 重启系统之后又出现

**Comment by SunBK201** [comment]
可以直接修改 yaml 中的 port，没有弊端

**Comment by gushi233** [comment]
OK 我想顺便问一下 我用了iptables过滤了和修改了一下流量出站规则实现防时钟偏移检测 IPID检测 的功能之类的  ，
我检查了里面的内容，没有使用1080端口的规则，他们和ua3f没有什么冲突把。

**Comment by SunBK201** [comment]
防时钟偏移检测 IPID 检测不会与 UA3F 产生冲突

**Comment by gushi233** [comment]
![QQ图片20241011202932](https://github.com/user-attachments/assets/4162e171-5b6e-47c3-9ce2-e23e19bb5c77)
![QQ图片20241011183603](https://github.com/user-attachments/assets/ab4dc584-3df2-48de-8cf0-12e24df28917)
![QQ图片20241008180011](https://github.com/user-attachments/assets/6f59a913-fe5e-439f-aeba-99fde49ffaa7)
![QQ图片20241008175929](https://github.com/user-attachments/assets/7df6f566-6545-4091-aa16-0aac201d1bb3)
![QQ图片20241011203326](https://github.com/user-attachments/assets/d6dea4d5-ff24-4751-9dc5-a2ed4a178df1)
大佬还是不行啊 显示还是原UA

**Comment by gushi233** [comment]
![Uploading ua3f.png…]()
为什么还是不行呢

**Comment by gushi233** [comment]
为什么还是不行呢
![ua3f](https://github.com/user-attachments/assets/1a41a27d-a827-473e-bffd-45d3541a52c7)
![clash](https://github.com/user-attachments/assets/32fcf3b0-51a1-44be-bc70-030fa0d9e8b8)
![QQ图片20241011211745](https://github.com/user-attachments/assets/26110607-a564-4f14-87be-ab548a6bcc23)

**Comment by gushi233** [comment]
配置文件和日志如下
![QQ图片20241011212431](https://github.com/user-attachments/assets/a58cb2f7-ea09-4afc-af5c-3a8d77254edb)
![QQ图片20241011212406](https://github.com/user-attachments/assets/9334df1b-5516-47f2-8577-325c41d4a9b3)

**Comment by SunBK201** [comment]
你的 Clash 启动似乎出现了 iptables 相关的错误，先确保 shellcrash 能够正常工作

**Comment by gushi233** [comment]
iptables 的错误解决了 但是似乎还是行不通
![QQ图片20241008180011](https://github.com/user-attachments/assets/23037d08-e921-43bb-9cca-f583a5134def)
![QQ图片20241013003827](https://github.com/user-attachments/assets/5ef84ea1-6559-4b87-bb7b-0daa37726fe7)
![QQ图片20241013004109](https://github.com/user-attachments/assets/5d1333ad-be37-4eff-8839-203e2c84ed22)
![QQ图片20241013004047](https://github.com/user-attachments/assets/e110567e-b5ba-4af6-b9e2-b1a7ac4bf6d4)

**Comment by gushi233** [comment]
这次也不报错了

**Comment by SunBK201** [comment]
测试时确保测试主机端没有代理目标测试网站

**Comment by gushi233** [comment]
我特别开了清除系统代理 并未开启代理目标测试网站

**Comment by gushi233** [comment]
我去，闹鬼了?日志和输出都是正常的，但为毛就是实现不了功能？

**Comment by gushi233** [comment]
我又测试了一边 还是不行....?

**Comment by gushi233** [comment]
![QQ图片20241013010147](https://github.com/user-attachments/assets/64ecd648-0357-4afd-b29a-9a9c1043469d)
啊，找到了 这个原因大概是什么呢?

**Comment by SunBK201** [comment]
这个地址你的网络无法访问，你可以尝试关闭UA3F和Clash，然后访问该地址，应该还是无法访问

**Comment by gushi233** [comment]
在 ua3f 和 clash 都运行的状态 路由器 和 主机可以可以ping通这个ip 
![QQ图片20241013115247](https://github.com/user-attachments/assets/decb3531-24f8-4683-92cd-5278a475fa34)

**Comment by SunBK201** [comment]
地址可以 ping 通不代表可以建立 tcp 连接，你需要尝试是否能够访问 13218 端口

**Comment by gushi233** [comment]
给我报403错误

**Comment by SunBK201** [comment]
只有日志中只有这个地址出现 connection refused 吗

**Comment by gushi233** [comment]
只看到了这个报错 而且有时候这个报错即使是不出现他也仍然不实现修改ua功能

**Comment by SunBK201** [comment]
这个准确只是 wanring，是预期异常，根本问题没有出在这里。能提供下完整日志吗。

**Comment by gushi233** [comment]
是ua3f的日志 还是 openwrt的日志呢

**Comment by gushi233** [comment]
我日志默认开始info模式

**Comment by SunBK201** [comment]
ua3f 开启 debug 看看

**Comment by gushi233** [comment]
不知道为什么 shellclash和ua3f同时运行会让路由器无响应过一会shellclash会自己崩溃掉，有时候这俩能同时运行但对ua修改不起任何作用。

**Comment by SunBK201** [comment]
可以试试 v0.6.0 该问题是否还存在？

**Comment by gushi233** [comment]
OK 我试试
