### ISSUE TITLE
v0.2.0 performance issue

### ISSUE THREAD

**Issue by SunBK201** [SunBK201/UA3F#3]
想问下更新了ua3f后，出现了开启openclash后很快，网络延迟就变得很高。cpu占用也变得很高。是因为新版本对硬件要求进一步提升了吗？之前使用0.13版本时cpu占用还是很低的。硬件是歌华链路由器，mt7621a。

_Originally posted by @sleepbad137 in https://github.com/SunBK201/UA3F/issues/1#issuecomment-1868228442_

**Comment by SunBK201** [comment]
@sleepbad137 v0.2.0 没有对硬件提升要求，请问你的测试方法是什么？

**Comment by sleepbad137** [comment]
> @sleepbad137 v0.2.0 没有对硬件提升要求，请问你的测试方法是什么？

没有测试过。只是更新完ua3f后出现了开启openclash后，网络延迟变高，表现在打开网页缓慢，并且openclash页面中的延迟显示到几千ms。同时出现openclash页面中cpu占用率相比更新前变高的现象。
与此对照的还有使用其他配置而非调用ua3f的配置时，使用调用ua3f的配置出现了cpu占用率高的现象。

**Comment by SunBK201** [comment]
使用 MT7621A 配合 shellclash 经过测试没有出现你所说的延迟到几千ms。
你可以尝试使用 shellclash 进行测试观察，或者可以选择回退版本：`https://github.com/SunBK201/UA3F/releases/tag/v0.1.3`，将 `/root/ua3f` 进行替换。

此外 UA3F 提供的 Clash 配置包含大量规则，因此流量在经过 Clash 时会进行规则匹配占用 CPU 是正常的。

**Comment by sleepbad137** [comment]
> 使用 MT7621A 配合 shellclash 经过测试没有出现你所说的延迟到几千ms。
> 你可以尝试使用 shellclash 进行测试观察，或者可以选择回退版本：`https://github.com/SunBK201/UA3F/releases/tag/v0.1.3`，将 `/root/ua3f` 进行替换。
> 
> 此外 UA3F 提供的 Clash 配置包含大量规则，因此流量在经过 Clash 时会进行规则匹配占用 CPU 是正常的。

好的，谢谢大佬。我去试一下回退后是否有这个问题。

**Comment by sleepbad137** [comment]
> 想问下更新了ua3f后，出现了开启openclash后很快，网络延迟就变得很高。cpu占用也变得很高。是因为新版本对硬件要求进一步提升了吗？之前使用0.13版本时cpu占用还是很低的。硬件是歌华链路由器，mt7621a。
> 
> _Originally posted by @sleepbad137 in https://github.com/SunBK201/UA3F/issues/1#issuecomment-1868228442_
>             

大佬，忘了问了，mt7621a选哪个文件啊？

**Comment by shiqu36** [comment]
> > 想问下更新了ua3f后，出现了开启openclash后很快，网络延迟就变得很高。cpu占用也变得很高。是因为新版本对硬件要求进一步提升了吗？之前使用0.13版本时cpu占用还是很低的。硬件是歌华链路由器，mt7621a。
> > _引用自  [in #1 （comment）](https://github.com/SunBK201/UA3F/issues/1#issuecomment-1868228442)_
> 
> 大佬，忘了问了，mt7621a选哪个文件啊？

看平台架构，releases里面有多个版本armv7 armv8
