### ISSUE TITLE
大佬 填写网页下提供的ua3f-cn.yaml（国内）时 启动clash提示

### ISSUE THREAD

**Issue by yhxaxy** [SunBK201/UA3F#30]
Clash服务没有运行（Redir模式），已设置开机启动！
TG频道：https://t.me/ShellClash
-----------------------------------------------
 1 启动/重启服务
 2 内核功能设置
 3 停止内核服务
 4 内核启动设置
 5 配置自动任务
 6 导入配置文件
 7 内核进阶设置
 8 其他工具
 9 更新/卸载
-----------------------------------------------
 0 退出脚本
请输入对应数字 > 1
-----------------------------------------------
服务已启动！
请使用 http://192.168.5.1:9999/ui 管理内置规则
[root@Kwrt:06:57 PM ~] # Warning: Extension REDIRECT revision 0 not supported, missing kernel module?
iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain shellcrash_dns
Warning: Extension REDIRECT revision 0 not supported, missing kernel module?
iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain shellcrash_dns
Warning: Extension REDIRECT revision 0 not supported, missing kernel module?
iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain shellcrash
Warning: Extension REDIRECT revision 0 not supported, missing kernel module?
iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain shellcrash

这个怎么办?  是链接填错了嘛？
我是选择  2 在线获取完整配置文件   然后填的   https://cdn.jsdelivr.net/gh/SunBK201/UA3F@master/clash/ua3f-cn.yaml

**Comment by yhxaxy** [comment]
----------------------------------------------
我确认遇到问题可以自行解决[1/0] > 1
-----------------------------------------------
仅限导入完整的配置文件链接！！！
-----------------------------------------------
有流媒体需求，请使用6-1在线生成配置文件功能！！！
如不了解机制，请使用6-1在线生成配置文件功能！！！
如遇任何问题，请使用6-1在线生成配置文件功能！！！
此功能可能会导致部分节点无法连接或者规则覆盖不完整！！！
-----------------------------------------------
0 返回上级菜单
-----------------------------------------------
请输入完整链接 > https://cdn.jsdelivr.net/gh/SunBK201/UA3F@master/clash/ua3f-cn.yaml
-----------------------------------------------
请检查输入的链接是否正确：
https://cdn.jsdelivr.net/gh/SunBK201/UA3F@master/clash/ua3f-cn.yaml
确认导入配置文件？原配置文件将被备份![1/0] > 1
-----------------------------------------------
链接地址为：https://cdn.jsdelivr.net/gh/SunBK201/UA3F@master/clash/ua3f-cn.yaml
可以手动复制该链接到浏览器打开并查看数据是否正常！
curl: (35) ssl_handshake returned - mbedTLS: (-0x7280) SSL - The connection indicated an EOF                                                                                   

######################################################################################################################################################################## 100.0%
已成功获取配置文件！
是否启动服务以使配置文件生效？(1/0) >

**Comment by yhxaxy** [comment]
链接地址为：https://cdn.jsdelivr.net/gh/SunBK201/UA3F@master/clash/ua3f-cn.yaml
可以手动复制该链接到浏览器打开并查看数据是否正常！
curl: (35) ssl_handshake returned - mbedTLS: (-0x7280) SSL - The connection indicated an EOF                                                                                   

######################################################################################################################################################################## 100.0%
已成功获取配置文件！
是否启动服务以使配置文件生效？(1/0) > 1
-----------------------------------------------
服务已启动！
请使用 http://192.168.5.1:9999/ui 管理内置规则
[root@Kwrt:07:05 PM ~] # Warning: Extension REDIRECT revision 0 not supported, missing kernel module?
iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain shellcrash_dns
Warning: Extension REDIRECT revision 0 not supported, missing kernel module?
iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain shellcrash_dns
Warning: Extension REDIRECT revision 0 not supported, missing kernel module?
iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain shellcrash
Warning: Extension REDIRECT revision 0 not supported, missing kernel module?
iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain shellcrash

**Comment by gushi233** [comment]
你这提示应该是缺了什么库 
试试`opkg update
opkg install kmod-ipt-redirect
`下载下缺少的库

**Comment by gushi233** [comment]
你这提示应该是缺了什么库
试试
`opkg update`
`opkg install kmod-ipt-redirect`
下载缺少的库

**Comment by yhxaxy** [comment]
> 你这提示应该是缺了什么库 试试  `OPKG 更新` `opkg install kmod-ipt-redirect` 下载缺少的库

[root@Kwrt:09:33 PM ~] # opkg install kmod-ipt-redirect
Unknown package 'kmod-ipt-redirect'.
Collected errors:
 * opkg_install_cmd: Cannot install package kmod-ipt-redirect.
[root@Kwrt:09:34 PM ~] #

**Comment by yhxaxy** [comment]
> 你这提示应该是缺了什么库 试试 `opkg update` `opkg install kmod-ipt-redirect` 下载缺少的库

# opkg update
opkg install kmod-ipt-redirect
Downloading https://dl.openwrt.ai/23.05/targets/ramips/mt7621/5.15.167/Packages.gz
Updated list of available packages in /var/opkg-lists/kwrt_core
Downloading https://dl.openwrt.ai/23.05/packages/mipsel_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/kwrt_base
Downloading https://dl.openwrt.ai/23.05/packages/mipsel_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/kwrt_packages
Downloading https://dl.openwrt.ai/23.05/packages/mipsel_24kc/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/kwrt_luci
Downloading https://dl.openwrt.ai/23.05/packages/mipsel_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/kwrt_routing
Downloading https://dl.openwrt.ai/23.05/packages/mipsel_24kc/kiddin9/Packages.gz
Updated list of available packages in /var/opkg-lists/kwrt_kiddin9
Unknown package 'kmod-ipt-redirect'.
Collected errors:
 * opkg_install_cmd: Cannot install package kmod-ipt-redirect.
 
  啊？

**Comment by MathLeee** [comment]
我成功了，你应该是防火墙模式错了，更改为Ntf基础试试，在内核功能设置里

**Comment by SunBK201** [comment]
该问题为 Clash 问题，可以向 [ShellCrash](https://github.com/juewuy/ShellCrash/issues)，[mihomo](https://github.com/MetaCubeX/mihomo/issues) 提问。
