### ISSUE TITLE
开启ua3f后，电脑使用clash for windows时，会使ua3f失效？

### ISSUE THREAD

**Issue by WWWyeye** [SunBK201/UA3F#31]
如题，当开启ua3f后，电脑不使用clash for windows，使用http://ua-check.stagoh.com/作为测试网站时，结果为FFF。
当使用https://ua.233996.xyz/作为测试网站时，使用clash for windows（如果不使用clash for windows科学上网，我好像打不开这个网站，手机电脑都一样，是我的问题吗），结果就失效了。
在shellclash中我使用的配置文件是https://cdn.jsdelivr.net/gh/SunBK201/UA3F@master/clash/ua3f-cn.yaml。需要改吗？
另外，请问如果我想开启防dpi检测法，目前还需要做其他措施吗
![第二个测试网站](https://github.com/user-attachments/assets/e5c76617-2f65-415d-be6e-a5b8e4bc7970)
![第一个测试网站](https://github.com/user-attachments/assets/c2c1352d-d6d6-4ea3-a718-46cd638ce815)

**Comment by yhxaxy** [comment]
哥么 你有遇见我那个问题嘛？ 编号33

**Comment by yhxaxy** [comment]
> 哥么 你有遇见我那个问题嘛？ 编号33

说错了 是编号#30

**Comment by WWWyeye** [comment]
> 哥么 你有遇见我那个问题嘛？ 编号33

你切成nft基础模式一下重新启动一下试试

**Comment by yhxaxy** [comment]
> > 哥么 你有遇见我那个问题嘛？ 编号33
> 
> 你切成nft基础模式一下重新启动一下试试

ok  是下课回寝室试试

**Comment by WWWyeye** [comment]
> > > 哥么 你有遇见我那个问题嘛？ 编号33
> > 
> > 你切成nft基础模式一下重新启动一下试试
> 
> ok  是下课回寝室试试

结果如何

**Comment by yhxaxy** [comment]
> > > > 哥么 你有遇见我那个问题嘛？ 编号33
> > > 
> > > 
> > > 你切成nft基础模式一下重新启动一下试试
> > 
> > 
> > ok  是下课回寝室试试
> 
> 结果如何


切换nft模式就可以了 没有报错  但是作者不是说要用Meta 内核嘛？   你也是破解校园网限制嘛？    我这里是锐捷  我就卡在ua3f这里和锐捷认证了

**Comment by WWWyeye** [comment]
> > > > > 哥么 你有遇见我那个问题嘛？ 编号33
> > > > 
> > > > 
> > > > 你切成nft基础模式一下重新启动一下试试
> > > 
> > > 
> > > ok  是下课回寝室试试
> > 
> > 结果如何
> 
> 
> 切换nft模式就可以了 没有报错  但是作者不是说要用Meta 内核嘛？   你也是破解校园网限制嘛？    我这里是锐捷  我就卡在ua3f这里和锐捷认证了
> 

不是一样可以切换内核吗，我是pppoe拨号的，但是还是会被检测到然后t下线。显示架设代理。

**Comment by SunBK201** [comment]
电脑使用 clash for windows，访问 ua 测试网站进行验证是否生效需要保证 clash for windows 没有代理 ua 测试网站。
如果需要防 dpi 检测法，使用 [ua3f-global-enhance.yaml](https://cdn.jsdelivr.net/gh/SunBK201/UA3F@master/clash/ua3f-global-enhance.yaml)
