### ISSUE TITLE
如何在国际增强版中加入自己的订阅的url呢

### ISSUE THREAD

**Issue by WWWyeye** [SunBK201/UA3F#32]
😃纯小白，需要用到什么软件和什么技术呢，有木有教程？🥰

**Comment by yhxaxy** [comment]
bilibili搜索校园网  那个封面最吸引人   播放时长十几分钟的那个  就是现在最详细的校园网破解教程，但可能会卡在认证这块

**Comment by WWWyeye** [comment]
> bilibili搜索校园网  那个封面最吸引人   播放时长十几分钟的那个  就是现在最详细的校园网破解教程，但可能会卡在认证这块

那个shellclash配置的u3f是国内的吧，我认为应该不生效？

**Comment by MathLeee** [comment]
> > bilibili搜索校园网  那个封面最吸引人   播放时长十几分钟的那个  就是现在最详细的校园网破解教程，但可能会卡在认证这块
> 
> 那个shellclash配置的u3f是国内的吧，我认为应该不生效？



> > bilibili搜索校园网  那个封面最吸引人   播放时长十几分钟的那个  就是现在最详细的校园网破解教程，但可能会卡在认证这块
> 
> 那个shellclash配置的u3f是国内的吧，我认为应该不生效？

确实不生效那里防火墙使用redir不生效改为nft网络又会出故障

**Comment by SunBK201** [comment]
在 proxy-providers > Global-ISP > url 中（第 23 行）加入你的代理节点订阅链接。
