### ISSUE TITLE
世界拒绝了我，ua3f日志里出现了“拒绝连接”/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by YeWenxuan64** [SunBK201/UA3F#34]
![屏幕截图 2024-10-11 200839](https://github.com/user-attachments/assets/d815428f-c0e1-4745-9e49-6b72bb260782)
嘤嘤

UA3F v0.4，修改的UA为Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/FFFFFFFFF

shellclash v稳定版1.8，redier模式，配置文件ua3f-cn.yaml

非法的issues嘤嘤

**Comment by SunBK201** [comment]
尝试关闭 UA3F 与 Clash 后，是否能与这些地址建立连接，如果无法建立连接说明你所处的网路环境本身无法访问这些地址。

**Comment by YeWenxuan64** [comment]
好问题，从浏览器上访问它提示“拒绝连接”，假如目标服务器拒绝我的连接，那ua3f会顺便报告是吗喵

**Comment by SunBK201** [comment]
是的

**Comment by SunBK201** [comment]
未来版本会尝试优化该类型日志报告

**Comment by SunBK201** [comment]
UA3F v0.5.0 已修复该日志问题
