### ISSUE TITLE
原有shellclash配置文件失效，导入配置文件后发生报错

### ISSUE THREAD

**Issue by 1437649480** [SunBK201/UA3F#38]
导入配置文件后发生具体如下图的报错，我的基本配置是MIPS 1004K从V2.15 CPU的新路由3，openwrt版本为23.05，内核版本为5.15.147，同样为在线shellclash稳定版cdn源，安装为meta内核，在线导入和本地导入后都报出如下图的错，恳求得到您的帮助，受限于设备损坏敬请谅解。
![808ff6cb2b3a2831ee2eb41f1fa8ebb](https://github.com/user-attachments/assets/62ef89f6-4bd3-4bad-aa62-119a6c37d592)
![微信图片_20241029233548](https://github.com/user-attachments/assets/65f2eb22-7e8a-4385-a2be-5ef3110697e3)

**Comment by SunBK201** [comment]
配置文件没问题，你的clash安装有问题，建议询问clash社区

**Comment by 1437649480** [comment]
好的，谢谢您。
