### ISSUE TITLE
搭配homeproxy（sing-box）无法正常使用

### ISSUE THREAD

**Issue by Jiang-lai** [SunBK201/UA3F#42]
环境如下
sing-box版本1.9.7-1
![图片](https://github.com/user-attachments/assets/0359fffd-6a9d-4d5e-b80e-7f71684e7bc4)
![图片](https://github.com/user-attachments/assets/a8aa3f06-3c37-4e0c-b278-57859365f909)
![图片](https://github.com/user-attachments/assets/e40b11f8-c4d8-4b3b-a5aa-03519da63784)

log如下 :

> [2024-11-12 23:40:53][INFO]: UA3F v0.6.0
> [2024-11-12 23:40:53][INFO]: Port: 1080
> [2024-11-12 23:40:53][INFO]: User-Agent: FFF
> [2024-11-12 23:40:53][INFO]: User-Agent Regex Pattern: (iPhone|iPad|Android|Macintosh|Windows|Linux|Apple|Mac OS X)
> [2024-11-12 23:40:53][INFO]: Enable Partial Replace: false
> [2024-11-12 23:40:53][INFO]: Log level: info
> [2024-11-12 23:40:53][INFO]: Listen on 127.0.0.1:1080
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files
> [2024-11-12 23:42:32][ERROR]: Accept failed: accept tcp 127.0.0.1:1080: accept4: too many open files

期间cpu异常占用，出现多个ua3f进程，以及当log过多的时候，luci出现崩溃，删除/var/log/ua3f.log后恢复
![图片](https://github.com/user-attachments/assets/727cd6d5-be35-4935-8e4b-2144e122be5c)

**Comment by SunBK201** [comment]
出现了流量回环，可以选择不要让 sing-box 接管本机流量

**Comment by Jiang-lai** [comment]
> 出现了流量回环，可以选择不要让 sing-box 接管本机流量

谢谢，把这回事忘了，我让UA3F进程走直连试试。
