### ISSUE TITLE
openclash+adguardhome使用其他配置时正常，但使用ua3f-cn.yaml会很卡。报错如下。

### ISSUE THREAD

**Issue by yzy1228682367** [SunBK201/UA3F#44]
4 | [warning] | [TCP] dial DIRECT (match ProcessName/ua3f) 172.18.31.173:55134(ua3f, uid=65534) --> 120.53.53.53:443 error: dial tcp 120.53.53.53:443: i/o timeout
-- | -- | --
3 | [warning] | [TCP] dial DIRECT (match ProcessName/ua3f) 172.18.31.173:36902(ua3f, uid=65534) --> 104.16.132.229:443 error: dial tcp 104.16.132.229:443: i/o timeout
2 | [warning] | [TCP] dial DIRECT (match ProcessName/ua3f) 172.18.31.173:36720(ua3f, uid=65534) --> 9.9.9.10:443 error: dial tcp 9.9.9.10:443: i/o timeout
1 | [warning] | [TCP] dial DIRECT (match ProcessName/ua3f) 192.168.1.216:50896(ua3f, uid=65534) --> 223.111.122.203:40013 error: dial tcp 223.111.122.203:40013: i/o timeout

517 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:55108 --> 8.8.4.4:443 error: EOF
-- | -- | --
516 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:59166(AdGuardHome) --> 94.140.14.14:443 error: EOF
515 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:55090(AdGuardHome) --> 8.8.4.4:443 error: EOF
514 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:51274(AdGuardHome) --> 9.9.9.10:443 error: EOF
513 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:56472(AdGuardHome) --> 9.9.9.10:443 error: EOF
512 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:53656(AdGuardHome) --> 104.16.132.229:443 error: EOF
511 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:44288(AdGuardHome) --> 8.8.4.4:443 error: EOF
510 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:44292(AdGuardHome) --> 8.8.4.4:443 error: EOF
509 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:53658(AdGuardHome) --> 104.16.132.229:443 error: EOF
508 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:53640(AdGuardHome) --> 104.16.132.229:443 error: EOF
507 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:47808(AdGuardHome) --> 8.8.4.4:443 error: EOF
506 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:44898(AdGuardHome) --> 94.140.14.14:443 error: EOF
505 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:56566(AdGuardHome) --> 9.9.9.10:443 error: EOF
504 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:44890(AdGuardHome) --> 94.140.14.14:443 error: EOF
503 | [warning] | [TCP] dial ua3f (match Match/) 192.168.1.216:50883 --> hm.baidu.com:443 error: EOF
502 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:53738(AdGuardHome) --> 104.16.132.229:443 error: EOF
501 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:34454(AdGuardHome) --> 94.140.14.14:443 error: EOF
500 | [warning] | [TCP] dial ua3f (match Match/) 172.18.31.173:51246(AdGuardHome) --> 9.9.9.10:443 error: EOF

**Comment by SunBK201** [comment]
如果只有 ua3f-cn.yaml 卡顿，说明你访问的部分域名需要代理访问。

**Comment by yzy1228682367** [comment]
> 如果只有 ua3f-cn.yaml 卡顿，说明你访问的部分域名需要代理访问。

多谢大佬，发现在adguardhome里把上游服务器Bootstrap DNS 服务器中的外国服务器去掉就可以啦。
