### ISSUE TITLE
Clash 配置报错

### ISSUE THREAD

**Issue by SunBK201** [SunBK201/UA3F#5]
`欢迎使用ShellClash！            版本：1.8.0
Clash服务没有运行（混合模式），已设置开机启动！
TG频道：https://t.me/ShellClash
-----------------------------------------------
 1 启动/重启clash服务
 2 clash功能设置
 3 停止clash服务
 4 clash启动设置
 5 设置定时任务
 6 导入配置文件
 7 clash进阶设置
 8 其他工具
 9 更新/卸载
-----------------------------------------------
 0 退出脚本
请输入对应数字 > 1
-----------------------------------------------
error msg="rules[2] [DOMAIN-SUFFIX,httpbin.org.CN] error: proxy [httpbin.org.CN] not found"
自定义配置文件校验失败！将使用基础配置文件启动！
错误详情请参考 /tmp/ShellClash/error.yaml 文件！
error msg="rules[2] [DOMAIN-SUFFIX,httpbin.org.CN] error: proxy [httpbin.org.CN] not found"
自定义配置文件校验失败！将使用基础配置文件启动！
错误详情请参考 /tmp/ShellClash/error.yaml 文件！
Clash服务启动失败！请查看报错信息！
error msg="rules[2] [DOMAIN-SUFFIX,httpbin.org.CN] error: proxy [httpbin.org.CN] not found"
/etc/clash/start.sh: line 1313: 13773 Killed                  /etc/init.d/clash start
[root@OpenWrt:09:11 PM ~] # `
clash 报错了怎么办

_Originally posted by @BilibiliLH in https://github.com/SunBK201/UA3F/issues/4#issuecomment-1871165960_

**Comment by SunBK201** [comment]
@BilibiliLH 请提供你的配置信息

**Comment by YeWenxuan64** [comment]
用户[BilibiliLH]他的配置是一台J1900 CPU的双网口工控机，openwrt版本为23.05.1，内核为5.15.137，安装UA3F使用的是线上安装（输入链接），安装Shellclash使用的是在线安装，版本为最新稳定版，源为jsDelivrCDN，内核meta。首次安装后它要求填写配置文件，我输入了ua3f README中提供的文件，之后的报错就是用户[BilibiliLH]截图的报错

**Comment by BilibiliLH** [comment]
是的， @YeWenxuan64 帮我进行配置，具体情况可以让她来反馈

**Comment by SunBK201** [comment]
@YeWenxuan64 @BilibiliLH 之前提供的 clash 配置需要修改导入自己的订阅链接，现在提供无需修改的配置 [ua3f-cn.yaml](https://cdn.jsdelivr.net/gh/SunBK201/UA3F@master/clash/ua3f-cn.yaml), 详见 [README](https://github.com/SunBK201/UA3F)。

**Comment by YeWenxuan64** [comment]
![bee9df042b00cbfecd675c922091050](https://github.com/SunBK201/UA3F/assets/60416781/b0520133-b785-4ad7-b425-6291a186570d)
![7a2880ad5072dec3ed1515fe54ad3f5](https://github.com/SunBK201/UA3F/assets/60416781/01b9a127-d303-4289-a61f-f5804700
![4a755c4c1b3d254cfcbc2eadb2ecbf2](https://github.com/SunBK201/UA3F/assets/60416781/6aae50c8-1a01-4482-9891-fe73a115ccad)
126c)
![9ffeac4c640efec615193087f215db2](https://github.com/SunBK201/UA3F/assets/60416781/c23ec07b-34e8-4c63-bf36-98d1ec7edcd1)
已经成功使用，棒ヾ(≧▽≦*)o
