### ISSUE TITLE
关于UA3F的功能建议

### ISSUE THREAD

**Issue by Po810C** [SunBK201/UA3F#6]
建议UA3F支持Tproxy或Redirect，可以更方便在小内存或储存设备上使用

**Comment by mengxin66** [comment]
大佬，想问问clash meta for android 怎么配置呢？用大佬提供的配置用了ua还是没改😭😭😭

**Comment by SunBK201** [comment]
> clash meta for android

ua3f 运行在 openwrt 上。另外有问题请另开 issue 。

**Comment by mengxin66** [comment]
好哦，谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月24日(周三) 晚上9:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SunBK201/UA3F] 关于UA3F的功能建议 (Issue #6)




  
clash meta for android
  
ua3f 运行在 openwrt 上。另外有问题请另开 issue 。
